<?php
/**
 * 
 * Table metadata for the Acme_Model_Comments model class.
 * 
 * This class is auto-generated by make-model; any changes you make will be
 * overwritten the next time you use make-model.  Modify the Acme_Model_Comments
 * class instead of this one.
 * 
 */
class Acme_Model_Comments_Metadata extends Acme_Sql_Model_Metadata
{
    public $table_name = 'comments';
    
    public $table_cols = array (
      'id' => array (
        'name' => 'id',
        'type' => 'mediumint',
        'size' => NULL,
        'scope' => NULL,
        'default' => NULL,
        'require' => true,
        'primary' => true,
        'autoinc' => true,
      ),
      'blog_id' => array (
        'name' => 'blog_id',
        'type' => 'smallint',
        'size' => NULL,
        'scope' => NULL,
        'default' => NULL,
        'require' => true,
        'primary' => false,
        'autoinc' => false,
      ),
      'title' => array (
        'name' => 'title',
        'type' => 'varchar',
        'size' => 60,
        'scope' => NULL,
        'default' => NULL,
        'require' => true,
        'primary' => false,
        'autoinc' => false,
      ),
      'content' => array (
        'name' => 'content',
        'type' => 'text',
        'size' => NULL,
        'scope' => NULL,
        'default' => NULL,
        'require' => true,
        'primary' => false,
        'autoinc' => false,
      ),
      'author' => array (
        'name' => 'author',
        'type' => 'varchar',
        'size' => 20,
        'scope' => NULL,
        'default' => NULL,
        'require' => true,
        'primary' => false,
        'autoinc' => false,
      ),
    );
    
    public $index_info = array (
    );
}
